name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release

  package-web:
    runs-on: [windows-latest]
    name: Create Web package
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Publish with dotnet
        run: dotnet publish --configuration Release --output publish-web FlightEvents.Web
      - name: Collect artifact
        uses: actions/upload-artifact@1.0.0
        with:
          name: Website package
          path: publish-web

  publish-web:
    runs-on: [windows-latest]
    name: Publish Web package
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Overwrite Secrets
        run: echo 'export const MAPBOX_API_KEY = "${{ secrets.MAPBOX_API_KEY }}"' > FlightEvents.Web/ClientApp/src/Constants.ts
      - name: Publish with dotnet
        run: dotnet publish --configuration Release --output publish-web FlightEvents.Web
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v2
        with:
          app-name: flightevents
          package: publish-web
          
  package-client:
    runs-on: [windows-latest]
    name: Package Client
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Publish with dotnet
        run: dotnet publish --configuration Release --output publish-client --runtime win-x86 --self-contained false /p:PublishSingleFile=true /p:PublishReadyToRun=true FlightEvents.Client
      - name: Copy extra content
        run: copy FlightEvents.Client/appsettings.Release.json publish-client/appsettings.json & copy FlightEvents.Client/README.txt publish-client/README.txt & dir publish-client
      - name: Collect artifact
        uses: actions/upload-artifact@1.0.0
        with:
          name: FlightEvents.Client
          path: publish-client
